services:
  

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: e18-p4-server:dev
    container_name: e18-p4-server
    # Server will read environment variables from ./server/.env
    # Edit ./server/.env (or create it from .env.example) to point ATLAS_URI appropriately
    env_file:
      - ./server/.env
    ports:
      - "5200:5200"
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local
